
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrpespcdsvqibwhzfetp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlycGVzcGNkc3ZxaWJ3aHpmZXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Mzc0OTIsImV4cCI6MjA1ODAxMzQ5Mn0.58Fr1ANSTydrKbiAIvoJwnP7jmYFSYVqCa5MeRZ71bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Custom type for our chat history data
export type ChatMessage = {
  id: number;
  sender: 'client' | 'me';
  content: string;
  time: string;
};

export type Conversation = {
  id: string;
  name: string;
  lastMessage: string;
  time: string;
  unread: number;
  avatar: string;
  phone: string;
  email: string | null;
  address: string | null;
  petName: string | null;
  petType: string | null;
  petBreed: string | null;
  sessionId: string;
};

// Define the possible structures of message data from n8n_chat_histories
export type MessageData = {
  role?: string;
  from?: string;
  sender?: string;
  text?: string;
  content?: { text?: string };
  message?: { text?: string };
  [key: string]: any;
};
